package com.myspace.cucumber_test_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaction_Needs_Review implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String transactionRefNumber;
	private java.lang.Boolean needsReview;

	private java.lang.Boolean secondLevelApprovalRequired;

	public Transaction_Needs_Review() {
	}

	public java.lang.String getTransactionRefNumber() {
		return this.transactionRefNumber;
	}

	public void setTransactionRefNumber(java.lang.String transactionRefNumber) {
		this.transactionRefNumber = transactionRefNumber;
	}

	public java.lang.Boolean getNeedsReview() {
		return this.needsReview;
	}

	public void setNeedsReview(java.lang.Boolean needsReview) {
		this.needsReview = needsReview;
	}

	public java.lang.Boolean getSecondLevelApprovalRequired() {
		return this.secondLevelApprovalRequired;
	}

	public void setSecondLevelApprovalRequired(
			java.lang.Boolean secondLevelApprovalRequired) {
		this.secondLevelApprovalRequired = secondLevelApprovalRequired;
	}

	public Transaction_Needs_Review(java.lang.String transactionRefNumber,
			java.lang.Boolean needsReview,
			java.lang.Boolean secondLevelApprovalRequired) {
		this.transactionRefNumber = transactionRefNumber;
		this.needsReview = needsReview;
		this.secondLevelApprovalRequired = secondLevelApprovalRequired;
	}

}