package com.myspace.cucumber_test_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaction_Needs_Review implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Transaction_Needs_Review() {
    }




}